#:kivy 1.9.0

PongGame:

<PongGame>:
    gameworld: _gameworld
    GameWorld:
        id: _gameworld
        gamescreenmanager: _gamescreenmanager
        size_of_gameworld: 100*1024
        size_of_entity_block: 128
        system_count: 2
        zones: {'general':10000}
    GameScreenManager:
        id: _gamescreenmanager
        gameworld: _gameworld
        size: root.size
        pos: root.pos
        GameScreen:
            name: 'main'
